project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Doushuai Palace"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/stardust1900
      - icon: twitter
        href: https://twitter.com/halfg0d
format:
  html:
    theme: cosmo
    css: styles.css