project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "王君敕的炼丹房"
  navbar:
    right:
      - text：首页
        href: https://wangxuan.me
      - about.qmd
      - icon: github
        href: https://github.com/stardust1900
      - icon: sina-weibo
        href: https://weibo.com/halfg0d
format:
  html:
    theme: cosmo
    css: styles.css