project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "兜率宫"
  navbar:
    right:
      - icon: house-fill
        href: https://wangxuan.me
      - icon: github
        href: https://github.com/stardust1900
      - icon: sina-weibo
        href: https://weibo.com/halfg0d
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css